### ISSUE TITLE
StringIndexOutOfBoundsException when trying to copy empty text

### ISSUE THREAD

**Issue by Ghostlyr** [MattCzyr/Notes#6]
Client crashes when clicking CTRL C by unselected text or empty text field:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at com.chaosthedude.notes.gui.GuiNoteTextField.getSelectedText(GuiNoteTextField.java:604)
	at com.chaosthedude.notes.gui.GuiNoteTextField.keyTyped(GuiNoteTextField.java:68)
	at com.chaosthedude.notes.gui.GuiEditNote.func_73869_a(GuiEditNote.java:108)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:319)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Mod version: 1.1.0
MC 1.7.10
Forge 1644

**Comment by MattCzyr** [comment]
Fixed in version 1.1.1.
