### ISSUE TITLE
java.io.FileNotFoundException if change the name of a pinned note

### ISSUE THREAD

**Issue by BatHeart** [MattCzyr/Notes#7]
The mod is working very smoothly and well, except for this.

If you:

1.  Create a note
2.  Pin it
3.  Edit the note, changing its name

There are then an endless series of errors thrown, of the format:

[18:33:41] [Client thread/INFO]: [STDERR]: java.io.FileNotFoundException: D:\Users\Xxxxxx\Downloads\Minecraft\MultiMC\instances\1.11.2 Forge\minecraft\notes\local\Test\New Note.txt (The system cannot find the file specified)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at java.io.FileInputStream.open0(Native Method)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at java.io.FileReader.<init>(FileReader.java:72)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at com.chaosthedude.notes.note.Note.update(Note.java:220)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at com.chaosthedude.notes.note.Note.update(Note.java:244)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at com.chaosthedude.notes.event.RenderTickHandler.onRenderTick(RenderTickHandler.java:23)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_RenderTickHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:359)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1079)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:53)
[18:33:41] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[18:33:41] [Client thread/INFO]: [STDERR]: 	at com.chaosthedude.notes.note.Note.update(Note.java:233)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at com.chaosthedude.notes.note.Note.update(Note.java:244)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at com.chaosthedude.notes.event.RenderTickHandler.onRenderTick(RenderTickHandler.java:23)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_RenderTickHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:359)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1079)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
[18:33:41] [Client thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:53)

This also causes the game to hang-up for about 1s every 2s.

**Comment by MattCzyr** [comment]
Fixed in version 1.1.1.

**Comment by BatHeart** [comment]
Thank you, sir, for the remarkably quick response and resolution!
